# Generated by Django 4.2.5 on 2023-09-27 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "mastery",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="portfolio/skills")),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, upload_to="portfolio/images"),
        ),
        migrations.AlterField(
            model_name="softskill",
            name="image",
            field=models.ImageField(upload_to="portfolio/softskills"),
        ),
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(to="portfolio.skill"),
        ),
    ]
