# Generated by Django 4.2.5 on 2023-09-28 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_skill_alter_project_image_alter_softskill_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="logo",
            field=models.FileField(
                blank=True,
                upload_to="portfolio/skills",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["svg", "jpeg", "jpg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="softskill",
            name="image",
            field=models.FileField(
                blank=True,
                upload_to="portfolio/softskills",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["svg", "jpeg", "jpg", "png"]
                    )
                ],
            ),
        ),
    ]
